export const categoryConstant = {
  GET_ALL_CATEGORY_REQUEST: "GET_ALL_CATEGORY_REQUEST",
  GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
  GET_ALL_CATEGORY_FAILURE: "GET_ALL_CATEGORY_FAILURE",
  ADD_NEW_CATEGORY_REQUEST: "ADD_NEW_CATEGORY_REQUEST",
  ADD_NEW_CATEGORY_SUCCESS: "ADD_NEW_CATEGORY_SUCCESS",
  ADD_NEW_CATEGORY_FAILURE: "ADD_NEW_CATEGORY_FAILURE",
  GET_ALL_CATEGORYLIST_REQUEST: "GET_ALL_CATEGORYLIST_REQUEST",
  GET_ALL_CATEGORYLIST_SUCCESS: "GET_ALL_CATEGORYLIST_SUCCESS",
  GET_ALL_CATEGORYLIST_FAILURE: "GET_ALL_CATEGORYLIST_FAILURE",
};

export const productConstaints = {
  GET_PRODUCTS_BY_SLUG: "GET_PRODUCTS_BY_SLUG",
};
