export const categoryConstant = {
  GET_ALL_CATEGORY_REQUEST: "GET_ALL_CATEGORY_REQUEST",
  GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
  GET_ALL_CATEGORY_FAILURE: "GET_ALL_CATEGORY_FAILURE",
  ADD_NEW_CATEGORY_REQUEST: "ADD_NEW_CATEGORY_REQUEST",
  ADD_NEW_CATEGORY_SUCCESS: "ADD_NEW_CATEGORY_SUCCESS",
  ADD_NEW_CATEGORY_FAILURE: "ADD_NEW_CATEGORY_FAILURE",
  GET_ALL_CATEGORYLIST_REQUEST: "GET_ALL_CATEGORYLIST_REQUEST",
  GET_ALL_CATEGORYLIST_SUCCESS: "GET_ALL_CATEGORYLIST_SUCCESS",
  GET_ALL_CATEGORYLIST_FAILURE: "GET_ALL_CATEGORYLIST_FAILURE",
};

export const productConstaints = {
  GET_PRODUCTS_BY_SLUG: "GET_PRODUCTS_BY_SLUG",
  GET_FEATURED_PRODUCT_REQUEST: "GET_FEATURED_PRODUCT_REQUEST",
  GET_FEATURED_PRODUCT_SUCCESS: "GET_FEATURED_PRODUCT_SUCCESS",
  GET_FEATURED_PRODUCT_FAILURE: "GET_FEATURED_PRODUCT_FAILURE",

  GET_FEATURED_PRODUCT_BY_CATEGORY_REQUEST:
    "GET_FEATURED_PRODUCT_BY_CATEGORY_REQUEST",
  GET_FEATURED_PRODUCT_BY_CATEGORY_SUCCESS:
    "GET_FEATURED_PRODUCT_BY_CATEGORY_SUCCESS",
  GET_FEATURED_PRODUCT_BY_CATEGORY_FAILURE:
    "GET_FEATURED_PRODUCT_BY_CATEGORY_FAILURE",
};
export const cartConstants = {
  ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
  RESTE_CART: "RESET_CART",
};

export const checkoutConstants = {
  ADD_ADDRESS_REQUEST: "ADD_ADDRESS_REQUEST",
  ADD_ADDRESS_SUCCESS: "ADD_ADDRESS_SUCCESS",
  ADD_ADDRESS_FAILURE: "ADD_ADDRESS_FAILURE",
  DELETE_ADDRESS_REQUEST: "DELETE_ADDRESS_REQUEST",
  DELETE_ADDRESS_SUCCESS: "DELETE_ADDRESS_SUCCESS",
  DELETE_ADDRESS_FAILURE: "DELETE_ADDRESS_FAILURE",
  EDIT_ADDRESS_REQUEST: "EDIT_ADDRESS_REQUEST",
  EDIT_ADDRESS_SUCCESS: "EDIT_ADDRESS_SUCCESS",
  EDIT_ADDRESS_FAILURE: "EDIT_ADDRESS_FAILURE",
};

export const orderConstants = {
  ADD_OREDER_REQUEST: "ADD_OREDER_REQUEST",
  ADD_OREDER_SUCCESS: "ADD_OREDER_SUCCESS",
  ADD_OREDER_FAILURE: "ADD_OREDER_FAILURE",
};
